### ISSUE TITLE
unable to run when --output is connected to syslog

### ISSUE THREAD

**Issue by flokli** [mechpen/sockdump#15]
I'm running socklog in a systemd service. By default, systemd connects this to the systemd journal, which works for most services.

I assumed it'd work with `hex` format too.

However, it fails with a "OSError: [Errno 6] No such device or address: '/dev/stdout'".

Same applies if I explicitly use `/proc/self/fd/1`.

**Comment by mechpen** [comment]
Fixed. Please verify.

**Comment by flokli** [comment]
Yes, this works. Thanks!
