### ISSUE TITLE
[Question] How to configure protocol?

### ISSUE THREAD

**Issue by dprogm** [mechpen/sockdump#21]
Hello everybody :wink: 

I want to use `sockdump` for analyzing traffic between a client and server communicating using the Some/IP protocol. My command is:

```bash
sudo ./sockdump.py "/tmp/vsomeip*" --format pcap --output someip
```

Then I am importing the file `someip` via wireshark. But it is not showing the expected traffic.

![wireshark_screenshot](https://github.com/mechpen/sockdump/assets/32619672/0bcd1df0-2bac-4110-b28c-427873693c14)

Do I need to write an extra lua script like this one: [wireshark/dummy.lua ](https://github.com/mechpen/sockdump/blob/0f1ff24410c96e409a811a85cb21d8f924fda520/wireshark/dummy.lua)?

Help is appreciated :relaxed:

**Comment by mechpen** [comment]
yes, you could try modify the dummy.lua

**Comment by dprogm** [comment]
@mechpen Okay. Thank you for the fast response. :wink:  I will try to figure out how to do it. I will close the issue as my question is answered.

**Comment by 123130** [comment]
@dprogm I have installed the dependencies of the sockdump, and run the command like "sudo ./sockdump.py /tmp/vsomeip* --format pcap --output someip", but there is an error like:
<img width="880" alt="image" src="https://github.com/mechpen/sockdump/assets/58681779/f9995618-0f69-4d81-bee7-105e38cb84be">
