### ISSUE TITLE
Failed to compile BPF module <text>

### ISSUE THREAD

**Issue by hailong9375** [mechpen/sockdump#22]
Traceback (most recent call last):
  File "./sockdump.py", line 412, in <module>
    main(args)
  File "./sockdump.py", line 353, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 347, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>

**Comment by lungj** [comment]
You may need the following packages (Debian/Ubuntu):

bcc bpfcc-tools python3-bpfcc linux-headers-$(uname -r)

**Comment by Ray-Eldath** [comment]
I've installed all packages described here and in [INSTALL.md of bcc](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary). this bug still shows. this may have something to do with a bug in the Ubuntu package bcc itself: https://bugs.launchpad.net/ubuntu/+source/bpfcc/+bug/1969626.

Hope things could be resolved soon.

**Comment by Ray-Eldath** [comment]
> I've installed all packages described here and in [INSTALL.md of bcc](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---binary). this bug still shows. this may have something to do with a bug in the Ubuntu package bcc itself: https://bugs.launchpad.net/ubuntu/+source/bpfcc/+bug/1969626.
> 
> Hope things could be resolved soon.

Actually I've successfully run `sockdump` on  Ubuntu 22.04 after I manually compile and install the bcc and python bindings according to the instruction [here](https://github.com/iovisor/bcc/blob/master/INSTALL.md#ubuntu---source).

**Comment by mechpen** [comment]
should be bcc library issue.  closing
