### ISSUE TITLE
Add information about what "socket path" is

### ISSUE THREAD

**Issue by mklepaczewski** [mechpen/sockdump#24]
# The problem
`usage: sockdump.py [-h] [--seg-size SEG_SIZE] [--segs-per-msg SEGS_PER_MSG] [--segs-in-buffer SEGS_IN_BUFFER] [--format {hex,hexstring,string,pcap}] [--output OUTPUT] sock`

The `<sock>` description is not detailed enough. It can't be any path leading to the socket, it seems to must be the path the process which created the socket used. This confused me for a while, as I'm using Docker & bind mounts to expose socket files to the host system from containers.

Soft links (and probably hard links) wouldn't work either.

# Example 
The socket created in the container has the path `/var/run/php-fpm.sock`, which is mapped to the path `/opt/app/var/run/php-fpm.sock` in the host system. When sniffing for traffic using `sockdump.py /opt/app/var/run/php-fpm.sock` no traffic is reported (i.e. only `waiting for data` is shown). `sockdump.py /var/run/php-fpm.sock` works fine though, even though the `/var/run/php-fpm.sock` socket doesn't exist from the host system perspective.

**Comment by mechpen** [comment]
Thanks for reporting the issue.  Fixed in https://github.com/mechpen/sockdump/commit/23401e1f7276d1c3b0a3d007728b507c9eaa5cc8
