### ISSUE TITLE
How to distinguish traffic on two different sockets with the same path?

### ISSUE THREAD

**Issue by mklepaczewski** [mechpen/sockdump#25]
# The problem

When using containers and isolated filesystems, two containers may create a socket with the same path, e.g., `/var/run/php-fpm.sock`. To capture traffic on these sockets, one has to use their paths as seen from container's perspective, i.e., `/var/run/php-fpm.sock`.

Is it possible to filter for traffic on a specific socket?

**Comment by mechpen** [comment]
Could use process ID to filter traffic.  Will add this feature later.
