### ISSUE TITLE
no member named 'iov' in 'struct iov_iter'

### ISSUE THREAD

**Issue by andrei-korshikov** [mechpen/sockdump#26]
In file included from arch/x86/include/asm/linkage.h:6:
    arch/x86/include/asm/ibt.h:77:8: warning: 'nocf_check' attribute ignored; use -fcf-protection to enable the attribute [-Wignored-attributes]
    extern __noendbr u64 ibt_save(bool disable);
           ^
    arch/x86/include/asm/ibt.h:32:34: note: expanded from macro '__noendbr'
    #define __noendbr       __attribute__((nocf_check))
                                           ^
    arch/x86/include/asm/ibt.h:78:8: warning: 'nocf_check' attribute ignored; use -fcf-protection to enable the attribute [-Wignored-attributes]
    extern __noendbr void ibt_restore(u64 save);
           ^
    arch/x86/include/asm/ibt.h:32:34: note: expanded from macro '__noendbr'
    #define __noendbr       __attribute__((nocf_check))
                                           ^
    /virtual/main.c:122:17: error: no member named 'iov' in 'struct iov_iter'
        iov = iter->iov;
              ~~~~  ^
    2 warnings and 1 error generated.

`uname --kernel-release`: **6.5.7**-zen1-1-zen

That's not a missing dependency, isn't it?

**Comment by jcelerier** [comment]
Same thing here

6.5.9-arch2-1.1 #1 SMP PREEMPT_DYNAMIC

OS: arch linux

**Comment by txelu** [comment]
And same for 6.5.9-zen2-1-zen

**Comment by mechpen** [comment]
should be fixed in https://github.com/mechpen/sockdump/commit/1d3fac6e82c97c5f303b4082edf036ec052a1164

**Comment by andrei-korshikov** [comment]
Tested on 6.5.7-zen1-1-zen, it works) Thanks a lot!
