### ISSUE TITLE
Error: cannot take the address of an rvalue of type

### ISSUE THREAD

**Issue by vlddm** [mechpen/sockdump#3]
```
/virtual/main.c:57:12: error: cannot take the address of an rvalue of type
      'typeof(struct iov_iter)' (aka 'struct iov_iter')
  ...&({ typeof(struct iov_iter) _val; memset(&_val, 0, sizeof(_val)); bpf_probe_read(&_val, sizeof(_val), (u64)&msg->msg_iter); _val; });
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Traceback (most recent call last):
  File "/root/bin/sockdump.py", line 306, in <module>
    main(args)
  File "/root/bin/sockdump.py", line 254, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 301, in __init__
    raise Exception("Failed to compile BPF module %s" % src_file)
Exception: Failed to compile BPF module 
```

Ubuntu 18.04.4 LTS
Python 3.6.9
libbpfcc                               0.5.0-5ubuntu1
python3-bpfcc                          0.5.0-5ubuntu1
libcc1-0:amd64                         8.4.0-1ubuntu1~18.04

**Comment by mechpen** [comment]
Is this working now? Or you just gave up :)

**Comment by salmon5** [comment]
The 0.5 version is too old,I have same error,I solved the problem use the following method(ubuntu 18.04):
sudo apt remove bpfcc-tools libbpfcc python3-bpfcc python-bpfcc
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4052245BD4284CDD
echo "deb https://repo.iovisor.org/apt/$(lsb_release -cs) $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/iovisor.list
sudo apt update
sudo apt install linux-headers-$(uname -r)
sudo apt install bcc-tools python3-bcc
