### ISSUE TITLE
No LICENSE

### ISSUE THREAD

**Issue by abulimov** [mechpen/sockdump#7]
First of all, thanks for the helpful tool.

Unfortunately as the project specifies no license, it's [dangerous from legal standpoint](https://choosealicense.com/no-permission/) to even use it, and definitely not safe to contribute to it.

Can you please consider specifying any open-source license? https://choosealicense.com/ is a good starting point.

Or otherwise explicitly mention that the code is copyrighted and should only be viewed.

**Comment by mechpen** [comment]
thanks! added license.
